/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "kcdfwxuyjjlkivhazkik"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtjZGZ3eHV5ampsa2l2aGF6a2lrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjczNjkzNjQsImV4cCI6MjA4Mjk0NTM2NH0.WOn0vv-sYiPZ_OHozwsYdUcpjXcldXodplvbs_Of-Wo"